In [1]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split as tts
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
df=load_breast_cancer()

In [10]:
#df

In [14]:
X,y=df.data,df.target

In [35]:
print("x var shape",df.data.shape)
print("y var shape",df.target.shape)

x var shape (569, 30)
y var shape (569,)


In [41]:
X[0]

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [15]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [16]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [17]:
X_train, X_test, y_train, y_test = tts(X, y, test_size=0.2, random_state=42)

In [21]:
X_train.shape[1]

30

In [23]:
#creating a sinle layer perceptron
model=keras.Sequential([layers.Input(shape=(30,)),
                        layers.Dense(1,activation="sigmoid")
                       ])

In [24]:
model.compile(optimizer="sgd",loss="binary_crossentropy",metrics=["accuracy"])

In [28]:
#model fitting
model.fit(X_train,y_train,epochs=100,batch_size=32, verbose=2)

Epoch 1/100
15/15 - 0s - loss: 89.8566 - accuracy: 0.8681 - 42ms/epoch - 3ms/step
Epoch 2/100
15/15 - 0s - loss: 107.4217 - accuracy: 0.8637 - 33ms/epoch - 2ms/step
Epoch 3/100
15/15 - 0s - loss: 98.3569 - accuracy: 0.8769 - 30ms/epoch - 2ms/step
Epoch 4/100
15/15 - 0s - loss: 80.6651 - accuracy: 0.8703 - 36ms/epoch - 2ms/step
Epoch 5/100
15/15 - 0s - loss: 96.1347 - accuracy: 0.8637 - 37ms/epoch - 2ms/step
Epoch 6/100
15/15 - 0s - loss: 61.3590 - accuracy: 0.8813 - 22ms/epoch - 1ms/step
Epoch 7/100
15/15 - 0s - loss: 107.1736 - accuracy: 0.8615 - 36ms/epoch - 2ms/step
Epoch 8/100
15/15 - 0s - loss: 96.1748 - accuracy: 0.8681 - 34ms/epoch - 2ms/step
Epoch 9/100
15/15 - 0s - loss: 138.4762 - accuracy: 0.8484 - 33ms/epoch - 2ms/step
Epoch 10/100
15/15 - 0s - loss: 204.5237 - accuracy: 0.8022 - 25ms/epoch - 2ms/step
Epoch 11/100
15/15 - 0s - loss: 126.1583 - accuracy: 0.8527 - 35ms/epoch - 2ms/step
Epoch 12/100
15/15 - 0s - loss: 92.6389 - accuracy: 0.8725 - 34ms/epoch - 2ms/step
Epoch 13

Epoch 100/100
15/15 - 0s - loss: 200.6810 - accuracy: 0.7846 - 36ms/epoch - 2ms/step


In [39]:
#evaluation
model.evaluate(X_test, y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

4/4 [==============================] - 0s 4ms/step - loss: 6.4270 - accuracy: 0.9561
Test Loss: 6.42703104019165
Test Accuracy: 0.9561403393745422
